type Project = {
	name: string;
	link: string;
	description: string;
}
const PROJECTS = [
	{
		name: "Dots and Circles",
		link: "https://dots-and-circles.sasha-m-ebersole.com/",
		repo: "https://github.com/AVespaIsNotAMotorcycle/dots-and-circles",
		description: "Dots and Circles is my first non-tutorial machine learning project. It is an app for optical character recognition of Manchu-language text.",
		problem: [
			"The Manchu script is written top-to-bottom, left-to-right. All letters within",
			"a word are connected to each other, and the shape of a letter changes based on",
			"its position within a word. This makes it quite difficult to break a word down",
			"into individual letters. Additionally, this problem was to be tackled without",
			"the help of a framework like PyTorch, since I wanted to get a better sence of",
			"how neural networks work under the hood.",
		].join(' '),
		approach: [
			"Training data was synthetically generated by rendering words in various fonts.",
			"In each word, each row of pixels was labelled with the corresponding unicode character.",
			"Pairs of neural networks predict which characters correspond to lines in an image.",
			"Each pair is specialized for a particular style of Manchu text.",
			"An RNN determines which pair to use for a given image by reading the image line by line.",
			"The final output is then collapsed from an array of tokens into a single word.",
		].join(' '),
		outcome: [
			"Manually labelling characters was time-intensive, resulting in a small training set.",
			"The lack of training data meant that the model was unable to effectively generalize",
			"to other words, resulting in low accuracy.",
			"In the future, I aim to rebuild this using an encoder/decoder model trained",
			"on entire words, allowing it to use existing datasets.",
		].join(' '),
		tags: ['OCR', 'CTC', 'Computer Vision', 'Python'],
	},
	{
		name: "Raschka LLM",
		link: "", // "http://raschka.sasha-m-ebersole.com/",
		repo: "https://github.com/AVespaIsNotAMotorcycle/Raschka-LLM",
		description: "A GPT-style LLM created by working through Sebastian Raschka's book 'How to Build a Large Language Model (From Scratch)'",
		problem: [
			"Prior to reading this book, I had no idea how LLMs worked under the hood.",
			"Additionally, I had no experience using PyTorch.",
			"By working through Raschka's book, I hoped to gain a deeper understanding",
			"of LLMs and deep learning in general.",
		].join(' '),
		approach: [
			"Working chapter by chapter, I implemented the LLM with PyTorch.",
			"Each chapter involved iterating upon some component of the GPT model, from a basic",
			"example to a full implementation. In the course of this process, I implemented token",
			"and position embedding, multi-head attention, layer normalization and shortcut layers,",
			"transformer blocks. Once this was done, the LLM was at first trained on a short story",
			"learning to predict the next word in a sequence. Finally, GPT-2's public weights",
			"were loaded and then fine-tuned for two tasks: spam classification and responding to",
			"plain language prompts.",
		].join(' '),
		outcome: [
			"Over the course of this book I learned a lot about model architecture and training,",
			"but the two big takeaways were the utility of transformers and an understanding of",
			"fine-tuning existing models. There are two projects I would love to apply these to:",
			"first, using transformers to create a model capable of machine translation between",
			"English and either Classical Chinese or Manchu. Second, combining RAG with fine-tuning",
			"to produce a model that can act as a reliable interface between a user and the Qing",
			"Vertable Records.",
		].join(' '),
		tags: ['PyTorch', 'LLMs', 'Deep Learning', 'Python'],
	},
];

type DetailProps = {
	title: string;
	content: string;
};
function Detail(props: DetailProps) {
	const { title, content } = props;
	if (!content) return <section />;
	return (
		<section>
			<h4>{title}</h4>
			<p>{content}</p>
		</section>
	);
}

type TagProps = {
	tags: string[];
}
function Tags(props: TagProps) {
	const { tags } = props;
	return (
		<ul className="tags">
			{tags.map((tag) => <li key={tag}>{tag}</li>)}
		</ul>
	);
}

type LinkProps = {
	to: string;
	name: string;
};
function Link(props: LinkProps) {
	const { to, name } = props;
	if (!to) return null;
	if (!name) return null;
	return <a href={to}>{name}</a>;
}

export default function Projects() {
	return (
		<section>
			<h2>Projects</h2>
			{PROJECTS.map((project) => (
				<section key={project.name} className="project-card">
					<div>
						<h3>{project.name}</h3>
						<Link to={project.link} name="Live app" />
						<Link to={project.repo} name="GitHub repo" />
					</div>
					<div>
						<p>{project.description}</p>
					</div>
					<div className="details">
						<Detail title="Problem" content={project.problem} />
						<Detail title="Approach" content={project.approach} />
						<Detail title="Next Steps" content={project.outcome} />
					</div>
					<Tags tags={project.tags} />
				</section>
			))}
		</section>
	)
}
