type Project = {
	name: string;
	link: string;
	description: string;
}
const PROJECTS = [
	{
		name: "Dots and Circles",
		link: "http://dots-and-circles.sasha-m-ebersole.com/",
		repo: "https://github.com/AVespaIsNotAMotorcycle/dots-and-circles",
		description: "Dots and Circles is my first non-tutorial machine learning project. It is an app for optical character recognition of Manchu-language text.",
		problem: [
			"The Manchu script is written top-to-bottom, left-to-right. All letters within",
			"a word are connected to each other, and the shape of a letter changes based on",
			"its position within a word. This makes it quite difficult to break a word down",
			"into individual letters. Additionally, this problem was to be tackled without",
			"the help of a framework like PyTorch, since I wanted to get a better sence of",
			"how neural networks work under the hood.",
		].join(' '),
		approach: [
			"Training data was synthetically generated by rendering words in various fonts.",
			"In each word, each row of pixels was labelled with the corresponding unicode character.",
			"Pairs of neural networks predict which characters correspond to lines in an image.",
			"Each pair is specialized for a particular style of Manchu text.",
			"An RNN determines which pair to use for a given image by reading the image line by line.",
			"The final output is then collapsed from an array of tokens into a single word.",
		].join(' '),
		outcome: [
			"Manually labelling characters, resulting in a small training set.",
			"The lack of training data meant that the model was unable to effectively generalize",
			"to other words, resulting in low accuracy.",
			"In the future, I aim to rebuild this using an encoder/decoder model trained",
			"on entire words, allowing it to use existing datasets.",
		].join(' '),
		tags: ['OCR', 'CTC', 'Computer Vision'],
	},
	{
		name: "Raschka LLM",
		link: "http://raschka.sasha-m-ebersole.com/",
		repo: "https://github.com/AVespaIsNotAMotorcycle/Raschka-LLM",
		description: "A GPT-style LLM created by working through Sebastian Raschka's book 'How to Build a Large Language Model (From Scratch)'",
	},
];

function Detail({ title, content }) {
	return (
		<section>
			<h4>{title}</h4>
			<p>{content}</p>
		</section>
	);
}

export default function Projects() {
	return (
		<section>
			<h2>Projects</h2>
			{PROJECTS.map((project) => (
				<section key={project.name} className="project-card">
					<div>
						<h3>{project.name}</h3>
						<a href={project.link}>Live app</a>
						<a href={project.repo}>GitHub repo</a>
					</div>
					<div>
						<p>{project.description}</p>
					</div>
					<div className="details">
						<Detail title="Problem" content={project.problem} />
						<Detail title="Approach" content={project.approach} />
						<Detail title="Next Steps" content={project.outcome} />
					</div>
				</section>
			))}
		</section>
	)
}
